import HeaderLinks from "./Header/HeaderLinks";
import Header from "./Header/page";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mumtaz Service Provider",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#f5f6fa]"}>
        <HeaderLinks />
        {children}
      </body>
    </html>
  );
}
